//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public Nullable<int> telephone_number { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string website { get; set; }
    }
}
