//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Recieving_Permission = new HashSet<Recieving_Permission>();
            this.Store_Item = new HashSet<Store_Item>();
        }
    
        public int item_id { get; set; }
        public string item_name { get; set; }
        public string item_code { get; set; }
        public string description { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> unit_id { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recieving_Permission> Recieving_Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store_Item> Store_Item { get; set; }
    }
}
