//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recieving_Permission
    {
        public int rp_no { get; set; }
        public Nullable<System.DateTime> rp_date { get; set; }
        public Nullable<int> rp_items_quantity { get; set; }
        public Nullable<System.DateTime> item_prod_date { get; set; }
        public Nullable<System.DateTime> item_exp_date { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> item_id { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
